version: '3.8'
services:

  frontend:
    image: node:14.16.1
    volumes:
      - ./frontend/.:/src/
    working_dir: /src
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      - app

  backend:
    image: gradle:6.9-jdk11
    volumes:
      - ./backend/:/app
    working_dir: /app
    command: sh run.sh
    depends_on:
      - db
    ports:
      - 8080:8080
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/seandroke?useSSL=false&allowPublicKeyRetrieval=true
    #   SPRING_DATASOURCE_USERNAME: sean
    #   SPRING_DATASOURCE_PASSWORD: droke 
    networks:
      - app

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - app

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    
volumes:
  db-data:

networks:
  app: